name: Cypress Tests

on: pull_request

env:
  CYPRESS_TODOIST_BASE_URL: ${{ secrets.CYPRESS_TODOIST_BASE_URL }}
  CYPRESS_TODOIST_EMAIL: ${{ secrets.CYPRESS_TODOIST_EMAIL }}
  CYPRESS_TODOIST_PASSWORD: ${{ secrets.CYPRESS_TODOIST_PASSWORD }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: todoist_env
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm i
          npm run cypress:run
